export const FETCH_CATEGORY_DATA_SUCCESS = "FETCH_CATEGORY_DATA_SUCCESS";
export const FETCH_CATEGORY_DATA_FAILURE = "FETCH_CATEGORY_DATA_FAILURE";
export const FETCH_CATEGORY_DATA = "FETCH_CATEGORY_DATA";
